#!/bin/bash

# Script pour configurer PayPal sur Render via API
# Note: Render nécessite une configuration manuelle via le dashboard

echo "📝 VARIABLES À CONFIGURER SUR RENDER"
echo "===================================="
echo ""
echo "🔗 Aller sur: https://dashboard.render.com"
echo ""
echo "1. Cliquer sur le service: gj-camp-website-1"
echo "2. Menu de gauche → Environment"
echo "3. Cliquer sur 'Add Environment Variable'"
echo ""
echo "Variable 1:"
echo "  Key: PAYPAL_CLIENT_ID"
echo "  Value: AdT-LwZtwJCWWY-mQxdypz0Ael6KiDY4Puw2QOrgppkh7379iy-cpwsC1a4u9RfSrQC9pqFX-FOFqWTb"
echo ""
echo "Variable 2:"
echo "  Key: PAYPAL_CLIENT_SECRET"
echo "  Value: EBGL8OQ0k2EvtVS1CVXvuJ99Lv42EN61bSkOgh3nStxB4f0Yx7Z-ScRzoYTSLEfb_M_OK9qnKPWm3WjV"
echo ""
echo "4. Cliquer sur 'Save Changes'"
echo "5. Le backend va redémarrer automatiquement (2-3 min)"
echo ""
echo "===================================="
echo "📝 VARIABLES À CONFIGURER SUR VERCEL"
echo "===================================="
echo ""
echo "🔗 Aller sur: https://vercel.com/dashboard"
echo ""
echo "1. Cliquer sur le projet frontend"
echo "2. Settings → Environment Variables"
echo "3. Ajouter:"
echo ""
echo "  Name: REACT_APP_PAYPAL_CLIENT_ID"
echo "  Value: AdT-LwZtwJCWWY-mQxdypz0Ael6KiDY4Puw2QOrgppkh7379iy-cpwsC1a4u9RfSrQC9pqFX-FOFqWTb"
echo "  Environments: ☑ Production ☑ Preview ☑ Development"
echo ""
echo "4. Save"
echo "5. Onglet Deployments → ... (3 points) → Redeploy"
echo ""
echo "⏱️  Attendre 5 minutes puis tester le paiement"
echo ""
