#!/bin/bash

echo "🔧 CONFIGURATION PAYPAL_MODE SUR RENDER"
echo "======================================="
echo ""
echo "❌ PROBLÈME IDENTIFIÉ:"
echo "Le backend utilise l'API PayPal PRODUCTION avec des credentials SANDBOX"
echo ""
echo "Les credentials sandbox ne fonctionnent qu'avec l'API sandbox."
echo ""
echo "✅ SOLUTION:"
echo "Ajouter la variable PAYPAL_MODE=sandbox sur Render"
echo ""
echo "📋 ÉTAPES:"
echo ""
echo "1️⃣ Allez sur https://dashboard.render.com"
echo ""
echo "2️⃣ Sélectionnez 'gj-camp-website-1' (backend)"
echo ""
echo "3️⃣ Cliquez sur 'Environment'"
echo ""
echo "4️⃣ Cliquez 'Add Environment Variable'"
echo ""
echo "5️⃣ Ajoutez:"
echo "   ┌─────────────────────┐"
echo "   │ Nom: PAYPAL_MODE    │"
echo "   │ Valeur: sandbox     │"
echo "   └─────────────────────┘"
echo ""
echo "6️⃣ Cliquez 'Save Changes'"
echo ""
echo "7️⃣ Render va redémarrer automatiquement (2 minutes)"
echo ""
echo "⏳ Attendez que le status passe à 'Live'"
echo ""
echo "✅ VÉRIFICATION:"
echo ""
echo "Après le redémarrage, testez:"
echo ""
echo "curl -s https://gj-camp-website-1.onrender.com/api/test/paypal-config | jq '.'"
echo ""
echo "Vous devriez voir:"
echo "  \"baseURL\": \"https://api-m.sandbox.paypal.com\""
echo ""
echo "Puis testez le paiement sur le site !"
echo ""
echo "📝 RÉSUMÉ DES VARIABLES PAYPAL NÉCESSAIRES:"
echo ""
echo "Variable              | Valeur"
echo "----------------------|----------------------------------------"
echo "PAYPAL_CLIENT_ID      | AdT-LwZtwJCWWY-mQxdypz0Ael6KiDY4Puw..."
echo "PAYPAL_CLIENT_SECRET  | EBGL8OQ0k2EvtVS1CVXvuJ99Lv42EN61bSk..."
echo "PAYPAL_MODE          | sandbox"
echo ""
echo "💡 NOTE:"
echo "Quand vous passerez en production avec de vrais paiements,"
echo "vous devrez:"
echo "  1. Créer une app PayPal en mode LIVE"
echo "  2. Obtenir les nouveaux CLIENT_ID et CLIENT_SECRET"
echo "  3. Changer PAYPAL_MODE=live"
echo ""
