#!/bin/bash
# Script de déploiement des notifications push en production

echo "🚀 Déploiement Notifications Push - Production"
echo "=============================================="
echo ""

# Clés VAPID
VAPID_PUBLIC="BKUW6rJDpbTGTbPZY6y0ldcjf3OwpzqOeLIh8DQyZ49EUkYnjHuWKRxoLhHRLyG6vM-aCKuNq2fArvZasobHU6I"
VAPID_PRIVATE="BpNAPhsFbOHMvGjcTI3-6om-jmYpx8bjD0PUwa152sk"
VAPID_EMAIL="mailto:contact@gjsdecrpt.fr"

echo "📋 ÉTAPE 1/3 - Configuration Render (Backend)"
echo "---------------------------------------------"
echo ""
echo "🔗 Ouvrez: https://dashboard.render.com"
echo ""
echo "1. Sélectionnez votre service backend 'gj-camp-backend'"
echo "2. Allez dans 'Environment'"
echo "3. Cliquez sur 'Add Environment Variable'"
echo "4. Ajoutez ces 3 variables:"
echo ""
echo "   Nom: VAPID_PUBLIC_KEY"
echo "   Valeur: $VAPID_PUBLIC"
echo ""
echo "   Nom: VAPID_PRIVATE_KEY"
echo "   Valeur: $VAPID_PRIVATE"
echo ""
echo "   Nom: VAPID_EMAIL"
echo "   Valeur: $VAPID_EMAIL"
echo ""
echo "5. Cliquez 'Save Changes'"
echo "6. Le service va redémarrer automatiquement"
echo ""
read -p "✅ Appuyez sur ENTRÉE quand c'est fait..."
echo ""

echo "📋 ÉTAPE 2/3 - Configuration Vercel (Frontend)"
echo "----------------------------------------------"
echo ""
echo "🔗 Ouvrez: https://vercel.com/dashboard"
echo ""
echo "1. Sélectionnez votre projet 'gj-camp-website'"
echo "2. Allez dans 'Settings' → 'Environment Variables'"
echo "3. Cliquez sur 'Add'"
echo "4. Ajoutez cette variable:"
echo ""
echo "   Nom: REACT_APP_VAPID_PUBLIC_KEY"
echo "   Valeur: $VAPID_PUBLIC"
echo "   Environments: Production, Preview, Development (cochez toutes)"
echo ""
echo "5. Cliquez 'Save'"
echo ""
read -p "✅ Appuyez sur ENTRÉE quand c'est fait..."
echo ""

echo "📋 ÉTAPE 3/3 - Redéploiement"
echo "----------------------------"
echo ""
echo "🔄 Vercel va redéployer automatiquement"
echo "🔄 Render a déjà redémarré"
echo ""
echo "Attendez 2-3 minutes puis testez:"
echo ""
echo "🧪 Test Backend:"
echo "   curl https://gj-camp-backend.onrender.com/api/health"
echo "   (Devrait répondre avec succès)"
echo ""
echo "🧪 Test Frontend:"
echo "   1. Allez sur https://gjsdecrpt.fr/profile"
echo "   2. Connectez-vous"
echo "   3. Section 'Notifications Push'"
echo "   4. Activez le toggle"
echo "   5. Autoriser les permissions du navigateur"
echo "   6. Une notification de test devrait apparaître"
echo ""
read -p "✅ Appuyez sur ENTRÉE pour terminer..."
echo ""

echo "✅ Configuration terminée !"
echo ""
echo "📝 Pour vérifier les logs:"
echo "   - Render: https://dashboard.render.com → Logs"
echo "   - Vercel: https://vercel.com → Deployments"
echo ""
echo "🐛 En cas de problème, consultez: NOTIFICATIONS_PUSH_CONFIG.md"
