#!/bin/bash

echo "🔍 DIAGNOSTIC ERREUR PAIEMENT PAYPAL 400"
echo "========================================"
echo ""

echo "Le paiement PayPal réussit côté frontend mais le backend renvoie 400."
echo ""
echo "Pour diagnostiquer, nous devons voir les logs du backend Render:"
echo ""
echo "📋 ÉTAPES:"
echo ""
echo "1️⃣ Allez sur https://dashboard.render.com"
echo "2️⃣ Sélectionnez 'gj-camp-website-1' (backend)"
echo "3️⃣ Cliquez sur 'Logs' dans le menu de gauche"
echo "4️⃣ Faites défiler jusqu'aux logs les plus récents"
echo "5️⃣ Cherchez les lignes qui contiennent:"
echo "   - '❌' (emoji croix rouge)"
echo "   - 'PayPal'"
echo "   - 'Error'"
echo "   - '400'"
echo ""
echo "6️⃣ Copiez-moi TOUTES les lignes d'erreur"
echo ""
echo "OU"
echo ""
echo "📱 Dans la console du navigateur:"
echo "1️⃣ Trouvez la ligne '❌ Réponse backend: Object'"
echo "2️⃣ Cliquez sur le triangle ▶ à gauche de 'Object'"
echo "3️⃣ Cela va déplier l'objet et montrer le message d'erreur"
echo "4️⃣ Copiez-moi le contenu complet, notamment:"
echo "   - message"
echo "   - error"
echo "   - details"
echo ""
echo "Exemple de ce que je recherche:"
echo "  {message: 'Paiement invalide', error: 'Order not found', ...}"
echo ""
