#!/bin/bash

echo "🖼️ FIX IMAGES ACTIVITÉS - Configuration Vercel"
echo "=============================================="
echo ""
echo "❌ PROBLÈME:"
echo "Les images s'affichent quand on tape l'URL directement, mais pas sur le site."
echo "→ Le frontend ne sait pas où chercher les images du backend"
echo ""
echo "✅ SOLUTION:"
echo "Configurer REACT_APP_API_URL sur Vercel"
echo ""
echo "📋 ÉTAPES:"
echo ""
echo "1️⃣ Allez sur https://vercel.com/dashboard"
echo ""
echo "2️⃣ Sélectionnez votre projet (gj-camp-website ou gjsdecrpt)"
echo ""
echo "3️⃣ Cliquez sur 'Settings' → 'Environment Variables'"
echo ""
echo "4️⃣ Cherchez si REACT_APP_API_URL existe déjà:"
echo "   - Si OUI → Modifiez sa valeur"
echo "   - Si NON → Cliquez 'Add New'"
echo ""
echo "5️⃣ Configurez:"
echo "   ┌────────────────────────────────────────────────┐"
echo "   │ Name:  REACT_APP_API_URL                       │"
echo "   │ Value: https://gj-camp-website-1.onrender.com  │"
echo "   │                                                 │"
echo "   │ ✅ Production                                   │"
echo "   │ ✅ Preview                                      │"
echo "   │ ✅ Development                                  │"
echo "   └────────────────────────────────────────────────┘"
echo ""
echo "6️⃣ Cliquez 'Save'"
echo ""
echo "7️⃣ Allez dans 'Deployments'"
echo ""
echo "8️⃣ Cliquez sur les 3 points '...' du dernier déploiement → 'Redeploy'"
echo ""
echo "9️⃣ Attendez 2-3 minutes (le build Vercel)"
echo ""
echo "✅ VÉRIFICATION:"
echo ""
echo "Une fois redéployé:"
echo "  1. Allez sur votre site"
echo "  2. F12 → Console"
echo "  3. Cherchez: '🔗 API URL configurée:'"
echo "  4. Devrait afficher: https://gj-camp-website-1.onrender.com"
echo "  5. Rechargez la page des activités"
echo "  6. Les images devraient s'afficher ✅"
echo ""
echo "💡 POURQUOI ?"
echo "Sans cette variable, le frontend utilise 'http://localhost:5000'"
echo "qui ne fonctionne pas en production."
echo ""
echo "Le fichier frontend/src/config/api.js utilise:"
echo "  export const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000';"
echo ""
echo "Avec la variable configurée, API_URL pointera vers le bon backend Render."
echo ""
