#!/bin/bash

echo "🔴 PROBLÈME CORS IDENTIFIÉ"
echo "=========================="
echo ""
echo "Le frontend Vercel (gj-camp-website-3fuu.vercel.app) ne peut pas"
echo "communiquer avec le backend Render car CORS bloque les requêtes."
echo ""
echo "CAUSE:"
echo "------"
echo "Le backend n'autorise que: https://www.gjsdecrpt.fr"
echo "Mais vous accédez via: https://gj-camp-website-3fuu.vercel.app"
echo ""
echo "SOLUTION:"
echo "---------"
echo "Ajouter les DEUX URLs dans la variable FRONTEND_URL sur Render"
echo ""
echo "📋 ÉTAPES À SUIVRE:"
echo ""
echo "1️⃣ Allez sur https://dashboard.render.com"
echo ""
echo "2️⃣ Sélectionnez le service 'gj-camp-website-1' (backend)"
echo ""
echo "3️⃣ Cliquez sur 'Environment'"
echo ""
echo "4️⃣ Trouvez la variable FRONTEND_URL et modifiez-la:"
echo ""
echo "   Ancienne valeur:"
echo "   ┌─────────────────────────────────────┐"
echo "   │ https://www.gjsdecrpt.fr            │"
echo "   └─────────────────────────────────────┘"
echo ""
echo "   Nouvelle valeur (ajoutez une virgule et la 2ème URL):"
echo "   ┌──────────────────────────────────────────────────────────────┐"
echo "   │ https://www.gjsdecrpt.fr,https://gj-camp-website-3fuu.vercel.app │"
echo "   └──────────────────────────────────────────────────────────────┘"
echo ""
echo "5️⃣ Cliquez 'Save Changes'"
echo ""
echo "6️⃣ Render va automatiquement redémarrer le backend (1-2 minutes)"
echo ""
echo "7️⃣ Attendez que le status passe à 'Live' (point vert)"
echo ""
echo "✅ VÉRIFICATION:"
echo ""
echo "Une fois le backend redémarré:"
echo "   1. Rechargez https://gj-camp-website-3fuu.vercel.app"
echo "   2. Appuyez sur F12 → Console"
echo "   3. Les erreurs CORS doivent disparaître"
echo "   4. Le carrousel doit afficher les images Cloudinary"
echo "   5. Le logo doit s'afficher"
echo "   6. La connexion doit fonctionner"
echo ""
echo "💡 ASTUCE:"
echo "Pour éviter ce problème, utilisez toujours votre domaine:"
echo "   https://www.gjsdecrpt.fr"
echo "au lieu de l'URL Vercel directe."
echo ""

# Test CORS après modification
echo "🔍 TEST CORS (après avoir fait la modification):"
echo ""
echo "Exécutez cette commande pour vérifier:"
echo ""
echo "curl -I -H \"Origin: https://gj-camp-website-3fuu.vercel.app\" \\"
echo "  https://gj-camp-website-1.onrender.com/api/health"
echo ""
echo "Vous devriez voir:"
echo "  access-control-allow-origin: https://gj-camp-website-3fuu.vercel.app"
echo ""
