#!/bin/bash

# Configuration UptimeRobot pour empêcher le sleep backend Render
# Date: 13 Janvier 2026

echo "🤖 CONFIGURATION UPTIMEROBOT - Empêcher Sleep Backend"
echo "====================================================="
echo ""
echo "📋 POURQUOI ?"
echo "Le plan gratuit Render met en veille les services après 15 min d'inactivité."
echo "UptimeRobot va pinger le backend toutes les 5 minutes pour le garder actif."
echo ""
echo "🔗 ÉTAPES DE CONFIGURATION"
echo ""
echo "1️⃣ Créer un compte UptimeRobot"
echo "   → Aller sur https://uptimerobot.com"
echo "   → Sign Up (gratuit)"
echo "   → Confirmer l'email"
echo ""
echo "2️⃣ Ajouter un nouveau monitor"
echo "   → Dashboard → Add New Monitor"
echo ""
echo "3️⃣ Configuration du monitor"
echo ""
echo "   Monitor Type: HTTP(s)"
echo "   ✅ Sélectionner HTTP(s)"
echo ""
echo "   Friendly Name: GJ Camp Backend"
echo "   ✅ Nom pour identifier le monitor"
echo ""
echo "   URL (or IP): https://gj-camp-website-1.onrender.com/api/health"
echo "   ✅ IMPORTANT: Utiliser l'endpoint /api/health"
echo ""
echo "   Monitoring Interval: Every 5 minutes"
echo "   ✅ Fréquence minimale sur le plan gratuit"
echo ""
echo "   Monitor Timeout: 30 seconds"
echo "   ✅ Temps d'attente maximum pour la réponse"
echo ""
echo "   HTTP Method: GET"
echo "   ✅ Méthode par défaut"
echo ""
echo "   Alert Contacts: (optionnel)"
echo "   ✅ Email pour être notifié si le backend tombe"
echo ""
echo "4️⃣ Sauvegarder"
echo "   → Create Monitor"
echo ""
echo "✅ RÉSULTAT"
echo "Le backend sera pingé toutes les 5 minutes et restera actif 24/7"
echo ""
echo "📊 STATISTIQUES"
echo "Après quelques heures, tu verras :"
echo "- Uptime %"
echo "- Response time (devrait être < 500ms)"
echo "- Nombre de requêtes"
echo ""
echo "⚡ AVANTAGES"
echo "✅ Backend toujours chaud (pas de cold start)"
echo "✅ Réponse instantanée pour les utilisateurs"
echo "✅ Détection automatique si le backend crashe"
echo "✅ Notifications par email en cas de problème"
echo ""
echo "🔍 VÉRIFICATION"
echo "Après config, attends 5-10 minutes puis vérifie :"
echo "curl https://gj-camp-website-1.onrender.com/api/health"
echo ""
echo "Devrait répondre immédiatement : {\"message\":\"✅ Backend fonctionnel\"}"
echo ""
